const jobData = [
  {
    "id": 1,
    "name": "job name",
    "description": "Frontend developer",
    "type": "Contract",
    "seniority": "Junior",
    "company": "Google",
    "category": "Frontend",
    "responsibility": [
      "Responsibility 1",
      "Responsibility 2",
      "Responsibility 3"
    ],
    "requirements": ["Requirement 1", "Requirement 2", "Requirement 3"],
    "techstack": ["React", "Ruby-on-rails", "Typescript", "Git", "Docker"],
    "location": "Singapore",
    "rating": 4.2,
    "timeAgo": "about 6 hours ago",
    "logoUrl": "https://companieslogo.com/img/orig/GOOG-0ed88f7c.png?t=1633218227",
  },
  {
    "id": 2,
    "name": "job name",
    "description": "Backend developer",
    "type": "Contract",
    "seniority": "Junior",
    "company": "Google",
    "category": "Backend",
    "responsibility": [
      "Responsibility 1",
      "Responsibility 2",
      "Responsibility 3"
    ],
    "requirements": ["Requirement 1", "Requirement 2", "Requirement 3"],
    "techstack": ["React", "Ruby-on-rails"],
    "location": "Singapore",
    "rating": 4.2,
    "timeAgo": "about 6 hours ago",
    "logoUrl": "https://companieslogo.com/img/orig/GOOG-0ed88f7c.png?t=1633218227",
  },
  {
    "id": 3,
    "name": "job name",
    "description": "Tech Lead (Fullstack development)",
    "type": "Contract",
    "seniority": "Junior",
    "company": "Google",
    "category": "Fullstack",
    "responsibility": [
      "Responsibility 1",
      "Responsibility 2",
      "Responsibility 3"
    ],
    "requirements": ["Requirement 1", "Requirement 2", "Requirement 3"],
    "techstack": ["React", "NodeJS"],
    "location": "Singapore",
    "rating": 4.2,
    "timeAgo": "about 6 hours ago",
    "logoUrl": "https://companieslogo.com/img/orig/GOOG-0ed88f7c.png?t=1633218227",
  },
  {
    "id": 4,
    "name": "job name",
    "description": "Fullstack developer",
    "type": "Contract",
    "seniority": "Junior",
    "company": "Google",
    "category": "Fullstack",
    "responsibility": [
      "Responsibility 1",
      "Responsibility 2",
      "Responsibility 3"
    ],
    "requirements": ["Requirement 1", "Requirement 2", "Requirement 3"],
    "techstack": ["React", "NodeJS"],
    "location": "Singapore",
    "rating": 4.2,
    "timeAgo": "about 6 hours ago",
    "logoUrl": "https://companieslogo.com/img/orig/GOOG-0ed88f7c.png?t=1633218227",
  },
  {
    "id": 5,
    "name": "job name",
    "description": "DevOps Engineer",
    "type": "Contract",
    "seniority": "Junior",
    "company": "Google",
    "category": "DevOps",
    "responsibility": [
      "Responsibility 1",
      "Responsibility 2",
      "Responsibility 3"
    ],
    "requirements": ["Requirement 1", "Requirement 2", "Requirement 3"],
    "techstack": ["React", "NodeJS"],
    "location": "Singapore",
    "rating": 4.2,
    "timeAgo": "about 6 hours ago",
    "logoUrl": "https://companieslogo.com/img/orig/GOOG-0ed88f7c.png?t=1633218227",
  },
  {
    "id": 6,
    "name": "job name",
    "description": "Data Scientist",
    "type": "Contract",
    "seniority": "Junior",
    "company": "Google",
    "category": "Data",
    "responsibility": [
      "Responsibility 1",
      "Responsibility 2",
      "Responsibility 3"
    ],
    "requirements": ["Requirement 1", "Requirement 2", "Requirement 3"],
    "techstack": ["React", "NodeJS"],
    "location": "Singapore",
    "rating": 4.2,
    "timeAgo": "about 6 hours ago",
    "logoUrl": "https://companieslogo.com/img/orig/GOOG-0ed88f7c.png?t=1633218227",
  },
  {
    "id": 7,
    "name": "job name",
    "description": "Marketing manager",
    "type": "Contract",
    "seniority": "Junior",
    "company": "Google",
    "category": "Marketing",
    "responsibility": [
      "Responsibility 1",
      "Responsibility 2",
      "Responsibility 3"
    ],
    "requirements": ["Requirement 1", "Requirement 2", "Requirement 3"],
    "techstack": ["React", "NodeJS"],
    "location": "Singapore",
    "rating": 4.2,
    "timeAgo": "about 6 hours ago",
    "logoUrl": "https://companieslogo.com/img/orig/GOOG-0ed88f7c.png?t=1633218227",
  },
  {
    "id": 8,
    "name": "job name",
    "description": "IOS developer",
    "type": "Contract",
    "seniority": "Junior",
    "company": "Google",
    "category": "IOS",
    "responsibility": [
      "Responsibility 1",
      "Responsibility 2",
      "Responsibility 3"
    ],
    "requirements": ["Requirement 1", "Requirement 2", "Requirement 3"],
    "techstack": ["React", "NodeJS"],
    "location": "Singapore",
    "rating": 4.2,
    "timeAgo": "about 6 hours ago",
    "logoUrl": "https://companieslogo.com/img/orig/GOOG-0ed88f7c.png?t=1633218227",
  },
  {
    "id": 9,
    "name": "job name",
    "description": "Android developer",
    "type": "Contract",
    "seniority": "Junior",
    "company": "Google",
    "category": "Android",
    "responsibility": [
      "Responsibility 1",
      "Responsibility 2",
      "Responsibility 3"
    ],
    "requirements": ["Requirement 1", "Requirement 2", "Requirement 3"],
    "techstack": ["React", "NodeJS"],
    "location": "Singapore",
    "rating": 4.2,
    "timeAgo": "about 6 hours ago",
    "logoUrl": "https://companieslogo.com/img/orig/GOOG-0ed88f7c.png?t=1633218227",
  },  {
    "id": 10,
    "name": "job name",
    "description": "Android developer 2",
    "type": "Contract",
    "seniority": "Junior",
    "company": "Google",
    "category": "Android",
    "responsibility": [
      "Responsibility 1",
      "Responsibility 2",
      "Responsibility 3"
    ],
    "requirements": ["Requirement 1", "Requirement 2", "Requirement 3"],
    "techstack": ["React", "NodeJS"],
    "location": "Singapore",
    "rating": 4.2,
    "timeAgo": "about 6 hours ago",
    "logoUrl": "https://companieslogo.com/img/orig/GOOG-0ed88f7c.png?t=1633218227",
  },
  {
    "id": 11,
    "name": "job name",
    "description": "Android developer 3",
    "type": "Contract",
    "seniority": "Junior",
    "company": "Google",
    "category": "Android",
    "responsibility": [
      "Responsibility 1",
      "Responsibility 2",
      "Responsibility 3"
    ],
    "requirements": ["Requirement 1", "Requirement 2", "Requirement 3"],
    "techstack": ["React", "NodeJS"],
    "location": "Singapore",
    "rating": 4.2,
    "timeAgo": "about 6 hours ago",
    "logoUrl": "https://companieslogo.com/img/orig/GOOG-0ed88f7c.png?t=1633218227",
  },
  {
    "id": 12,
    "name": "job name",
    "description": "Android developer 4",
    "type": "Contract",
    "seniority": "Junior",
    "company": "Google",
    "category": "Android",
    "responsibility": [
      "Responsibility 1",
      "Responsibility 2",
      "Responsibility 3"
    ],
    "requirements": ["Requirement 1", "Requirement 2", "Requirement 3"],
    "techstack": ["React", "NodeJS"],
    "location": "Singapore",
    "rating": 4.2,
    "timeAgo": "about 6 hours ago",
    "logoUrl": "https://companieslogo.com/img/orig/GOOG-0ed88f7c.png?t=1633218227",
  },
  {
    "id": 13,
    "name": "job name",
    "description": "Android developer 5",
    "type": "Contract",
    "seniority": "Junior",
    "company": "Google",
    "category": "Android",
    "responsibility": [
      "Responsibility 1",
      "Responsibility 2",
      "Responsibility 3"
    ],
    "requirements": ["Requirement 1", "Requirement 2", "Requirement 3"],
    "techstack": ["React", "NodeJS"],
    "location": "Singapore",
    "rating": 4.2,
    "timeAgo": "about 6 hours ago",
    "logoUrl": "https://companieslogo.com/img/orig/GOOG-0ed88f7c.png?t=1633218227",
  },
  {
    "id": 14,
    "name": "job name",
    "description": "Android developer 6",
    "type": "Contract",
    "seniority": "Junior",
    "company": "Google",
    "category": "Android",
    "responsibility": [
      "Responsibility 1",
      "Responsibility 2",
      "Responsibility 3"
    ],
    "requirements": ["Requirement 1", "Requirement 2", "Requirement 3"],
    "techstack": ["React", "NodeJS"],
    "location": "Singapore",
    "rating": 4.2,
    "timeAgo": "about 6 hours ago",
    "logoUrl": "https://companieslogo.com/img/orig/GOOG-0ed88f7c.png?t=1633218227",
  },
  {
    "id": 15,
    "name": "job name",
    "description": "Android developer 7",
    "type": "Contract",
    "seniority": "Junior",
    "company": "Google",
    "category": "Android",
    "responsibility": [
      "Responsibility 1",
      "Responsibility 2",
      "Responsibility 3"
    ],
    "requirements": ["Requirement 1", "Requirement 2", "Requirement 3"],
    "techstack": ["React", "NodeJS"],
    "location": "Singapore",
    "rating": 4.2,
    "timeAgo": "about 6 hours ago",
    "logoUrl": "https://companieslogo.com/img/orig/GOOG-0ed88f7c.png?t=1633218227",
  },

]

export default jobData